name: PDCItemSetter
version: '0.1'
main: dev.oguzok.pDCItemSetter.PDCItemSetter
api-version: '1.21'
commands:
  pdcitemsetter:
    permission: pdcitemsetter.use
    aliases:
      - pdc
      - persistentdatacontainer
